### ISSUE TITLE
Final group capstone - Set up your Kanban board

### ISSUE THREAD

**Issue by Donard97** [Donard97/code-buddy-backend#9]
_**We opened this issue to review our Kanban board if it is as requested.**_ 👀 

_This issue is open to review my Kanban Boards. Here are the links:_
[Frontend Board](https://github.com/ahzia/code-buddy-frontend/projects/1)

![image](https://user-images.githubusercontent.com/74506933/150403400-6477536b-967e-4d3c-a1ee-f3b3e6aa01a5.png)

[Backend Board](https://github.com/Donard97/code-buddy-backend/projects/1)

![image](https://user-images.githubusercontent.com/74506933/150403327-e2696816-3a09-41f5-b49f-a012d8cec8bb.png)

- Our team has 2 members:
         @Donard97  & @ahzia 

### Project requirements that are done

- Create an empty repository for your group project. ✔️ 
- Open the GitHub project (Kanban board) in your team repo ✔️ 
- Create cards based on the [project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md) ✔️ 
- Each of the team members should assign themselves to the cards ✔️ 

<hr>

_Feel free to review our Kanban Board and if u have any questions please ask me!_ ✌️

**Comment by MuriloRoque** [comment]
Hi @Donard97, @ahzia,

Good job so far!
There are some issues that you still need to work on to move forward but you are almost there!

## Suggested changes

- [x] Please add a screenshot of your kanban boards to this Issue description.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issues for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Donard97** [comment]
@MuriloRoque Thank you for the feedback. I added the screenshots of the boards! ✌️

**Comment by MuriloRoque** [comment]
Hi @Donard97, @ahzia,

In my opinion, your project is complete! There is nothing else to say other than... it's time to start it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
